### ISSUE TITLE
Error circuit

### ISSUE THREAD

**Issue by dpeter99** [amadornes/SCM-Localization-Issues#140] opened 2016-11-07 14:59 UTC
Me again
Link:
https://gist.github.com/fe70d3c91447661168079a5174712d59
![2016-11-07_15 59 14](https://cloud.githubusercontent.com/assets/7725817/20062221/300aa31e-a503-11e6-94aa-7a8a137a6653.png)

**Comment by LolHens** [comment] 2016-11-07 17:12
I have an NPE at the same position:
[](https://gist.github.com/anonymous/fe70d3c91447661168079a5174712d59)

**Comment by amadornes** [comment] 2016-11-07 21:23
Duplicate of #136. Already fixed :)

**Closed by amadornes** 2016-11-07 21:23 UTC
Labels: Bug, Duplicate
