### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by maginator** [amadornes/SCM-Localization-Issues#105] opened 2016-11-06 10:18 UTC
If i try to Uploading a crash circuit with the multi meter the server crash.
Crash Report : http://pastebin.com/ASPyzMXS

Magi

**Comment by amadornes** [comment] 2016-11-06 11:49
Yep... As I imagined, this is caused by posts... Fixed in the next build :)

**Closed by amadornes** 2016-11-06 11:49 UTC
Labels: Bug
