### ISSUE TITLE
Illegal Argument Exception: Payload may not be larger than 32767

### ISSUE THREAD

**Issue by bigbaddevil7** [amadornes/SCM-Localization-Issues#171] opened 2016-11-09 22:43 UTC
When trying to make circuits within circuits I run into an issue that if I place more than 3 in a line side by side it will close the server side of my game (Im in SSP) and give me this
![errorpayload](https://cloud.githubusercontent.com/assets/1343455/20157562/552bc440-a69b-11e6-977a-9ab3c4c3ad38.png)

This is the circuit layout 
![example](https://cloud.githubusercontent.com/assets/1343455/20157581/6adb464e-a69b-11e6-819e-e48b53494394.png)

**Comment by amadornes** [comment] 2016-11-09 22:49
Duplicate of #98. It should be fixed in 1.0.3, which came out a few minutes ago.

**Closed by amadornes** 2016-11-09 22:49 UTC
Labels: Bug, Duplicate
