### ISSUE TITLE
Vertical colored wire

### ISSUE THREAD

**Issue by dpeter99** [amadornes/SCM-Localization-Issues#180] opened 2016-11-10 14:34 UTC
![2016-11-10_15 31 26](https://cloud.githubusercontent.com/assets/7725817/20180555/3800d304-a75b-11e6-9874-6a6b18d76ffd.png)

**Comment by amadornes** [comment] 2016-11-10 14:57
Duplicate of #160

**Closed by amadornes** 2016-11-10 14:57 UTC
Labels: Bug, Duplicate
