### ISSUE TITLE
Crash after breaking a circuit

### ISSUE THREAD

**Issue by elwooha6** [amadornes/SCM-Localization-Issues#143] opened 2016-11-07 19:08 UTC
So I was making a vertical circuit, tried to color a tiny redstone that was on the bottom edge of the circuit. Below the circuit is a redstone lamp. When I try to apply the color it doesn't apply and stays the default color. When I try to remove the tiny redstone, or break the whole circuit, I get the following crash.

[http://pastebin.com/KmVhgWV4](http://pastebin.com/KmVhgWV4)

**Comment by amadornes** [comment] 2016-11-07 21:53
Duplicate of #136. Fixed in 1.0.3 :)

**Closed by amadornes** 2016-11-07 21:53 UTC
Labels: Bug, Duplicate
