### ISSUE TITLE
Circuit inside Circuit

### ISSUE THREAD

**Issue by Nezbro** [amadornes/SCM-Localization-Issues#130] opened 2016-11-07 02:31 UTC
Crashed when I added circuit inside circuit

https://gist.github.com/anonymous/472594a8c885b9cf0750ae6ef3776e77

**Comment by amadornes** [comment] 2016-11-07 21:21
Same crash as #133, and again a duplicate of #136 :P

**Closed by amadornes** 2016-11-07 21:21 UTC
Labels: Bug, Duplicate
