### ISSUE TITLE
Wire state not updated if going through a "diode"

### ISSUE THREAD

**Issue by AndyLun** [amadornes/SCM-Localization-Issues#101] opened 2016-11-06 07:27 UTC
How to reproduce the problem :
Step 1 : Place down this circuit as shown
![image](https://cloud.githubusercontent.com/assets/3786228/20035997/bf169aba-a434-11e6-9a00-443d6e7c75f3.png)

Step 2 : Create a "diode" junction by shift-clicking wire with screwdriver
![image](https://cloud.githubusercontent.com/assets/3786228/20036005/036fdcf8-a435-11e6-8e66-0212a6f567c2.png)

Step 3 : Turn on the lever. Notice the right side of circuit is not on (it should)
![image](https://cloud.githubusercontent.com/assets/3786228/20036011/2392e9da-a435-11e6-9a07-326f6779504f.png)

However, if I "block update" any part of the wire on the right side, it turns on. (eg. placing another wire)
![image](https://cloud.githubusercontent.com/assets/3786228/20036013/3ca5cfc8-a435-11e6-92ce-f02fac4f6e95.png)
... and the same goes for turning off.
![image](https://cloud.githubusercontent.com/assets/3786228/20036014/46a5f430-a435-11e6-9679-afd2eaf13fc8.png)

Good luck fixing the bug :)

**Comment by amadornes** [comment] 2016-11-06 12:01
Duplicate of #48, already fixed ;)

**Closed by amadornes** 2016-11-06 12:01 UTC
Labels: Bug, Duplicate
