### ISSUE TITLE
Multimeter opens GUIs but mouse stays hidden

### ISSUE THREAD

**Issue by heldplayer** [amadornes/SCM-Localization-Issues#79] opened 2016-11-05 17:29 UTC
Right clicking configurable components with a multimeter opens the GUI to configure the component, but doesn't make the mouse show up again.

Example with a constant: https://ss.heldplayer.blue/INOu93ot

**Comment by GirafiStudios** [comment] 2016-11-05 17:31
Duplicate of https://github.com/amadornes/SCM-Localization-Issues/issues/59

**Closed** 2016-11-05 17:35 UTC
