### ISSUE TITLE
Random connections when recoloring a cable

### ISSUE THREAD

**Issue by gDKdev** [amadornes/SCM-Localization-Issues#139] opened 2016-11-07 12:40 UTC
When i recolor a normal cable next to a bundled cable (not connected) it automatically creates the unwanted connection between the normal and the bundled on - version 1.0.2, on the memory array from my first submission (#95?)

**Comment by amadornes** [comment] 2016-11-07 18:10
Duplicate of #111

**Closed by amadornes** 2016-11-07 18:10 UTC
Labels: Bug, Duplicate
